config/routes.rb
Rails.application.routes.draw do
  resources :cars
  resources :ratings
  resources :criteria_rankings
  resources :users
  resources :criteria
  root to: 'pages#about'
end

app/controllers/criteria_controller.rb
class CriteriaController < ApplicationController
  before_action :set_criterium, only: [:show, :edit, :update, :destroy]
  before_action :get_all_users, only: [:index, :new, :edit]
  
  # GET /criteria
  # GET /criteria.json
  def index
    @criteria = Criterium.all
  end

  # GET /criteria/1
  # GET /criteria/1.json
  # def show
  # end

  # GET /criteria/new
  def new
    @criterium = Criterium.new
  end

  # GET /criteria/1/edit
  def edit
  end

  # POST /criteria
  # POST /criteria.json
  def create
    @criterium = Criterium.new(criterium_params)

    respond_to do |format|
      if @criterium.save
        format.html { redirect_to criteria_path, notice: 'Criterium was successfully created.' }
        format.json { render :show, status: :created, location: @criterium }
      else
        format.html { render :new }
        format.json { render json: @criterium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /criteria/1
  # PATCH/PUT /criteria/1.json
  def update
    respond_to do |format|
      if @criterium.update(criterium_params)
        format.html { redirect_to criteria_path, notice: 'Criterium was successfully updated.' }
        format.json { render :show, status: :ok, location: @criterium }
      else
        format.html { render :edit }
        format.json { render json: @criterium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /criteria/1
  # DELETE /criteria/1.json
  def destroy
    @criterium.destroy
    respond_to do |format|
      format.html { redirect_to criteria_url, notice: 'Criterium was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_criterium
      @criterium = Criterium.find(params[:id])
    end
    
    def get_all_users
      @users = User.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def criterium_params
      params.require(:criterium).permit(:name, :comments,
        criteria_ranking_attributes: [:id, :user_id, :ranking, :notes])
    end
    
end

app/helpers/criteria_helper.rb
module CriteriaHelper
end

app/views/criteria/_form.html.erb
<%= simple_form_for(@criterium) do |cr| %>
  <%= cr.error_notification %>

  <div class="form-inputs">
    <%= cr.input :name %>
    <%= cr.input :comments %>
  </div>

  <div class="form-actions">
    <%= cr.button :submit %>
  </div>
<% end %>

app/views/criteria/edit.html.erb
<h1>Editing Criterium</h1>

<%= render 'form' %>
<br>
<%= link_to 'Back', criteria_path %>

app/views/criteria/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Criteria</h1>

<table>
	<thead>
		<tr>
			<th>Name</th>
			<% @users.each do |user| %>
				<th><%= user.name %></th>
			<% end %>
			<th>Comments</th>
			<th colspan="3"></th>
		</tr>
	</thead>

	<tbody>
		<% @criteria.each do |criterium| %>
			<tr>
				<td class="left"><%= link_to criterium.name, edit_criterium_path(criterium) %></td>
				<% @users.each do |user| %>
					<% cr = user.criteria_rankings.find_by(criterium_id: criterium.id) %>
					<td>
						<% if cr.present? %>
							<% if cr.ranking.present? %>
								<b><%= link_to " #{cr.ranking} ", edit_criteria_ranking_path(cr) %></b>
							<% else %>
								<%= link_to "add ", edit_criteria_ranking_path(cr) %>
							<% end %>
							<% if cr.notes.present? %>
								<a><span title="<%= cr.notes %>">...</span></a>
							<% end %>
						<% else %>
							<%= link_to "add", new_criteria_ranking_path(user_id: user.id, criterium_id: criterium.id) %>
						<% end %>
					</td>
				<% end %>
				<td class="left"><%= criterium.comments %></td>
				<td><%= link_to 'Delete', criterium, method: :delete, data: { confirm: 'Are you sure?' } %></td>
			</tr>
		<% end %>
	</tbody>
</table>

<br>

<%= link_to 'New Criterium', new_criterium_path %>

app/views/criteria/new.html.erb
<h1>New Criterium</h1>

<%= render 'form' %>
<br>
<%= link_to 'Back', criteria_path %>