config/routes.rb
Rails.application.routes.draw do
  resources :cars
  resources :ratings
  resources :criteria_rankings
  resources :users
  resources :criteria
  root to: 'pages#about'
end

app/models/car.rb
class Car < ActiveRecord::Base
	has_many :ratings, dependent: :destroy
	
	validates :name, uniqueness: { case_sensitive: false }

end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
	before_action :set_car, only: [:show, :edit, :update, :destroy]
	before_action :get_all_users, only: [:show]
	before_action :get_all_criteria, only: [:show]

	# GET /cars
	# GET /cars.json
	def index
		@cars = Car.all
	end

	# GET /cars/1
	# GET /cars/1.json
	def show
		# Create a hash of user weighted ratings (where both rating and criteria ranking exists)
		@weighted_ratings = Hash.new(0)
	end

	# GET /cars/new
	def new
		@car = Car.new
	end

	# GET /cars/1/edit
	def edit
	end

	# POST /cars
	# POST /cars.json
	def create
		@car = Car.new(car_params)

		respond_to do |format|
			if @car.save
				format.html { redirect_to @car, notice: 'Car was successfully created.' }
				format.json { render :show, status: :created, location: @car }
			else
				format.html { render :new }
				format.json { render json: @car.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /cars/1
	# PATCH/PUT /cars/1.json
	def update
		respond_to do |format|
			if @car.update(car_params)
				format.html { redirect_to @car, notice: 'Car was successfully updated.' }
				format.json { render :show, status: :ok, location: @car }
			else
				format.html { render :edit }
				format.json { render json: @car.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /cars/1
	# DELETE /cars/1.json
	def destroy
		@car.destroy
		respond_to do |format|
			format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
			format.json { head :no_content }
		end
	end

	private
		# Use callbacks to share common setup or constraints between actions.
		def set_car
			@car = Car.find(params[:id])
		end

		def get_all_users
			@users = User.all
		end

		def get_all_criteria
			@criteria = Criterium.all
		end

		# Never trust parameters from the scary internet, only allow the white list through.
		def car_params
			params.require(:car).permit(:name, :year, :price, :kilometrage, :current_owner, :phone, :address)
		end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_form.html.erb
<%= simple_form_for(@car) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :year %>
    <%= f.input :price %>
    <%= f.input :kilometrage %>
    <%= f.input :current_owner %>
    <%= f.input :phone %>
    <%= f.input :address %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Editing Car</h1>

<%= render 'form' %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cars</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Year</th>
      <th>Price</th>
      <th>Kilometrage</th>
      <th>Current owner</th>
      <th>Phone</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cars.each do |car| %>
      <tr>
        <td><%= link_to car.name, car %></td>
        <td><%= car.year %></td>
        <td><%= car.price %></td>
        <td><%= car.kilometrage %></td>
        <td><%= car.current_owner %></td>
        <td><%= car.phone %></td>
        <td><%= car.address %></td>
        <td><%= link_to 'Edit', edit_car_path(car) %></td>
        <td><%= link_to 'Delete', car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Car', new_car_path %>

app/views/cars/new.html.erb
<h1>New Car</h1>

<%= render 'form' %>

<%= link_to 'Back', cars_path %>

app/views/cars/show.html copy.erb
<p id="notice"><%= notice %></p>

<h1><%= @car.name %></h1>

<p><strong>Year:</strong> <%= @car.year %></p>

<p><strong>Price:</strong> <%= @car.price %></p>

<p><strong>Kilometrage:</strong> <%= @car.kilometrage %></p>

<p><strong>Current owner:</strong> <%= @car.current_owner %></p>

<p><strong>Phone:</strong> <%= @car.phone %></p>

<p><strong>Address:</strong> <%= @car.address %></p>

<h2>Listing Car Ratings</h2>

<table>
  <thead>
    <tr>
      <th>Criterium</th>
      <% @users.each do |user| %>
        <th><%= user.name %></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @criteria.each do |criterium| %>
      <tr>
        <td><%= link_to criterium.name, edit_criterium_path(criterium) %></td>
        <% @users.each do |user| %>
          <%= rating = user.criteria_rankings.find_by(criterium_id: criterium.id).rating %>
          <td><%= if rating.present? then rating.rating end %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', cars_path %>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @car.name %></h1>

<table>
	<thead>
		<tr>
			<th>Year</th>
			<th>Price</th>
			<th>Kilometrage</th>
			<th>Current owner</th>
			<th>Phone</th>
			<th>Address</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td><%= @car.year %></td>
			<td><%= @car.price %></td>
			<td><%= @car.kilometrage %></td>
			<td><%= @car.current_owner %></td>
			<td><%= @car.phone %></td>
			<td><%= @car.address %></td>
			<td>&nbsp;<%= link_to "Edit Details", edit_car_path(@car) %></td>
		</tr>
	</tbody>
</table>

<br>
<%= link_to 'New Car', new_car_path %>

<h2>User ratings for this car:</h2>

<table>
	<thead>
		<tr>
			<th></th>
			<% @users.each do |user| %>
				<th colspan="3"><%= user.name %></th>
			<% end %>
		</tr>
		<tr>
			<th>Criterium</th>
			<% @users.each do |user| %>
				<th>Rating</th>
				<th>Rank</th>
				<th>Weighted</th>
			<% end %>
		</tr>
	</thead>
	<tbody>
		<% @criteria.each do |criterium| %>
			<tr>
				<td class="left"><%= link_to criterium.name, edit_criterium_path(criterium) %></td>
				<% @users.each do |user| %>
				
					<!-- Find first (and only, hopefully!) rating with this car, criterium, and user: -->
					<% this_rating = @car.ratings.find_by(criterium_id: criterium.id, user_id: user.id) %>
					<% if this_rating.present? %>
						<td>
							<% if this_rating.rating.present? %>
								<b><%= link_to " #{this_rating.rating} ", edit_rating_path(this_rating) %></b>
							<% else %>
								<%= link_to "add ", edit_rating_path(this_rating) %>
							<% end %>
							<% if this_rating.notes.present? %>
								<a><span title="<%= this_rating.notes %>">...</span></a>
							<% end %>
						</td>
						
					<% else %>
						<td>
							<%= link_to "add", new_rating_path(car_id: @car.id, user_id: user.id, criterium_id: criterium.id) %>
						</td>
					<% end %>

					<!-- Print the "CR" (criteria ranking) and user rating for this user & criterium: -->
					<td><em>
						<%= CriteriaRanking.get_ranking_where(criterium_id: criterium.id, user_id: user.id) %>
					</em></td>

					<!-- Get the weighted rating, print it, and shove it into the @weighted_ratings hash: -->
					<% if this_rating.present? %>
						<% @weighted_ratings[criterium_id: criterium.id, user_id: user.id] = 
							this_rating.weighted_rating.to_f %>
						<td>
							<%= sprintf( "%.1f", @weighted_ratings[criterium_id: criterium.id, user_id: user.id] ) %>
						</td>
					<% else %>
						<td></td>
					<% end %>
				<% end %>
			</tr>
		<% end %>

		<tr>  <!-- Now print the final row with the total rating per user: -->
			<th>Total rating:</th>
			<% @users.each do |user| %>
				<% user_weighted_ratings = @weighted_ratings.select {|k,v| k[:user_id] == user.id} %>
				<td colspan="2"></td>
				<td><strong>
					<%= sprintf( "%.1f", user_weighted_ratings.values.reduce(:+) / 
						user_weighted_ratings.size ) %>
				</strong></td>
			<% end %>
		</tr>
	</tbody>
</table>